# Site settings
title: jason's github page
email: ccqngu@gmail.com
baseurl: "/foright.github.io" # the subpath of your site, e.g. /blog/
url: "http://foright.github.io" # the base hostname & protocol for your site
github_username: foright
# Build settings
markdown: kramdown
